close all;
Umath = Uout.signals(1).values;
Uswitch = Uout.signals(2).values;
Imath = Iout.signals(1).values;
Iswitch = Iout.signals(2).values;
Dtable = Iout.signals(1).values;
figure;
hold on;
plot(tout,Uswitch,'LineWidth',2);
plot(tout,Umath,'--','LineWidth',2);
grid on, grid minor;
ylim([0,200]);
hold off;
legend({'U_{Switch}','U_{Math}'},'Location','east','FontSize',16);
figure;
hold on;
plot(tout,Iswitch,'LineWidth',2);
plot(tout,Imath,'--','LineWidth',2);
grid on, grid minor;
ylim([0,100]);
hold off;
legend({'I_{Switch}','I_{Math}'},'Location','east','FontSize',16);